// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfsTGai6w0XWouKqHwFqMNPIcUfN_ZV1c',
    appId: '1:1092459992595:web:6e3a556c9f62ed467d91e6',
    messagingSenderId: '1092459992595',
    projectId: 'photonotes-pz32',
    authDomain: 'photonotes-pz32.firebaseapp.com',
    storageBucket: 'photonotes-pz32.firebasestorage.app',
    measurementId: 'G-4QPMFRVSQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGvk2FuTXOuhj2QYq3LggrECYkfq46evw',
    appId: '1:1092459992595:android:898ac024d85eaa9b7d91e6',
    messagingSenderId: '1092459992595',
    projectId: 'photonotes-pz32',
    storageBucket: 'photonotes-pz32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5zycgZ66oGRL6CTIhdbXIHr-OaK8fGY',
    appId: '1:1092459992595:ios:ab862007181cb0de7d91e6',
    messagingSenderId: '1092459992595',
    projectId: 'photonotes-pz32',
    storageBucket: 'photonotes-pz32.firebasestorage.app',
    androidClientId: '1092459992595-ltemund86q7ae96g7javhefe214i2h8h.apps.googleusercontent.com',
    iosClientId: '1092459992595-mlv31s9ake501a2gt0k7ejps05jucifm.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv5zycgZ66oGRL6CTIhdbXIHr-OaK8fGY',
    appId: '1:1092459992595:ios:ab862007181cb0de7d91e6',
    messagingSenderId: '1092459992595',
    projectId: 'photonotes-pz32',
    storageBucket: 'photonotes-pz32.firebasestorage.app',
    androidClientId: '1092459992595-ltemund86q7ae96g7javhefe214i2h8h.apps.googleusercontent.com',
    iosClientId: '1092459992595-mlv31s9ake501a2gt0k7ejps05jucifm.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfsTGai6w0XWouKqHwFqMNPIcUfN_ZV1c',
    appId: '1:1092459992595:web:cb6acd0e60dce20d7d91e6',
    messagingSenderId: '1092459992595',
    projectId: 'photonotes-pz32',
    authDomain: 'photonotes-pz32.firebaseapp.com',
    storageBucket: 'photonotes-pz32.firebasestorage.app',
    measurementId: 'G-V1D464SNTM',
  );

}